# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            asif
tagline:          'A Jekyll Theme'
# The description is used in the meta description tag (_includes/head.html).
# If you want to use it in the sidebar, uncomment its code under the tagline
# in _includes/sidebar.html
description:      'A Jekyll theme based on the original Hyde and the refreshed Hydeout.'
url:              https://mdasifjoardar.github.io
baseurl:          

author:
  name:           'John Devine'
  url:            https://mdasifjoardar.github.io

paginate:         3
plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

github:
  repo:           https://github.com/mdasifjoardar/mdasifjoardar.github.io
